/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as OnboardingWorkerRouteImport } from './routes/onboarding.worker'
import { Route as OnboardingEmployerRouteImport } from './routes/onboarding.employer'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as EmployerDashboardRouteImport } from './routes/employer.dashboard'
import { Route as ChatApplicationIdRouteImport } from './routes/chat.$applicationId'
import { Route as EmployerJobsIndexRouteImport } from './routes/employer.jobs.index'
import { Route as EmployerJobsNewRouteImport } from './routes/employer.jobs.new'
import { Route as EmployerJobsJobIdApplicantsRouteImport } from './routes/employer.jobs.$jobId.applicants'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWorkerRoute = OnboardingWorkerRouteImport.update({
  id: '/onboarding/worker',
  path: '/onboarding/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingEmployerRoute = OnboardingEmployerRouteImport.update({
  id: '/onboarding/employer',
  path: '/onboarding/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerDashboardRoute = EmployerDashboardRouteImport.update({
  id: '/employer/dashboard',
  path: '/employer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatApplicationIdRoute = ChatApplicationIdRouteImport.update({
  id: '/chat/$applicationId',
  path: '/chat/$applicationId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerJobsIndexRoute = EmployerJobsIndexRouteImport.update({
  id: '/employer/jobs/',
  path: '/employer/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerJobsNewRoute = EmployerJobsNewRouteImport.update({
  id: '/employer/jobs/new',
  path: '/employer/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerJobsJobIdApplicantsRoute =
  EmployerJobsJobIdApplicantsRouteImport.update({
    id: '/employer/jobs/$jobId/applicants',
    path: '/employer/jobs/$jobId/applicants',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/chat/$applicationId': typeof ChatApplicationIdRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/onboarding/employer': typeof OnboardingEmployerRoute
  '/onboarding/worker': typeof OnboardingWorkerRoute
  '/jobs/': typeof JobsIndexRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/employer/jobs/': typeof EmployerJobsIndexRoute
  '/employer/jobs/$jobId/applicants': typeof EmployerJobsJobIdApplicantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/chat/$applicationId': typeof ChatApplicationIdRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/onboarding/employer': typeof OnboardingEmployerRoute
  '/onboarding/worker': typeof OnboardingWorkerRoute
  '/jobs': typeof JobsIndexRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/employer/jobs': typeof EmployerJobsIndexRoute
  '/employer/jobs/$jobId/applicants': typeof EmployerJobsJobIdApplicantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/chat/$applicationId': typeof ChatApplicationIdRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/onboarding/employer': typeof OnboardingEmployerRoute
  '/onboarding/worker': typeof OnboardingWorkerRoute
  '/jobs/': typeof JobsIndexRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/employer/jobs/': typeof EmployerJobsIndexRoute
  '/employer/jobs/$jobId/applicants': typeof EmployerJobsJobIdApplicantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/saved'
    | '/signup'
    | '/chat/$applicationId'
    | '/employer/dashboard'
    | '/jobs/$jobId'
    | '/onboarding/employer'
    | '/onboarding/worker'
    | '/jobs/'
    | '/employer/jobs/new'
    | '/employer/jobs/'
    | '/employer/jobs/$jobId/applicants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/saved'
    | '/signup'
    | '/chat/$applicationId'
    | '/employer/dashboard'
    | '/jobs/$jobId'
    | '/onboarding/employer'
    | '/onboarding/worker'
    | '/jobs'
    | '/employer/jobs/new'
    | '/employer/jobs'
    | '/employer/jobs/$jobId/applicants'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/saved'
    | '/signup'
    | '/chat/$applicationId'
    | '/employer/dashboard'
    | '/jobs/$jobId'
    | '/onboarding/employer'
    | '/onboarding/worker'
    | '/jobs/'
    | '/employer/jobs/new'
    | '/employer/jobs/'
    | '/employer/jobs/$jobId/applicants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedRoute: typeof SavedRoute
  SignupRoute: typeof SignupRoute
  ChatApplicationIdRoute: typeof ChatApplicationIdRoute
  EmployerDashboardRoute: typeof EmployerDashboardRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  OnboardingEmployerRoute: typeof OnboardingEmployerRoute
  OnboardingWorkerRoute: typeof OnboardingWorkerRoute
  JobsIndexRoute: typeof JobsIndexRoute
  EmployerJobsNewRoute: typeof EmployerJobsNewRoute
  EmployerJobsIndexRoute: typeof EmployerJobsIndexRoute
  EmployerJobsJobIdApplicantsRoute: typeof EmployerJobsJobIdApplicantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/worker': {
      id: '/onboarding/worker'
      path: '/onboarding/worker'
      fullPath: '/onboarding/worker'
      preLoaderRoute: typeof OnboardingWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/employer': {
      id: '/onboarding/employer'
      path: '/onboarding/employer'
      fullPath: '/onboarding/employer'
      preLoaderRoute: typeof OnboardingEmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/dashboard': {
      id: '/employer/dashboard'
      path: '/employer/dashboard'
      fullPath: '/employer/dashboard'
      preLoaderRoute: typeof EmployerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$applicationId': {
      id: '/chat/$applicationId'
      path: '/chat/$applicationId'
      fullPath: '/chat/$applicationId'
      preLoaderRoute: typeof ChatApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/jobs/': {
      id: '/employer/jobs/'
      path: '/employer/jobs'
      fullPath: '/employer/jobs/'
      preLoaderRoute: typeof EmployerJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/jobs/new': {
      id: '/employer/jobs/new'
      path: '/employer/jobs/new'
      fullPath: '/employer/jobs/new'
      preLoaderRoute: typeof EmployerJobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/jobs/$jobId/applicants': {
      id: '/employer/jobs/$jobId/applicants'
      path: '/employer/jobs/$jobId/applicants'
      fullPath: '/employer/jobs/$jobId/applicants'
      preLoaderRoute: typeof EmployerJobsJobIdApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedRoute: SavedRoute,
  SignupRoute: SignupRoute,
  ChatApplicationIdRoute: ChatApplicationIdRoute,
  EmployerDashboardRoute: EmployerDashboardRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  OnboardingEmployerRoute: OnboardingEmployerRoute,
  OnboardingWorkerRoute: OnboardingWorkerRoute,
  JobsIndexRoute: JobsIndexRoute,
  EmployerJobsNewRoute: EmployerJobsNewRoute,
  EmployerJobsIndexRoute: EmployerJobsIndexRoute,
  EmployerJobsJobIdApplicantsRoute: EmployerJobsJobIdApplicantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
